name: Build macOS x64

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-macos-x64:
    runs-on: macos-13
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build shared packages
        run: |
          pnpm --filter @mcp_router/shared run build
          pnpm --filter @mcp_router/remote-api-types run build

      - name: Build Electron app (macOS x64)
        run: pnpm --filter @mcp_router/electron run make:x64

      - name: Determine release metadata
        id: release_meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            tag="${GITHUB_REF#refs/tags/}"
          else
            pkg_version=$(node -p "require('./package.json').version")
            tag="v${pkg_version}"
          fi
          echo "tag_name=${tag}" >> "$GITHUB_OUTPUT"
          echo "release_name=${tag}" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release_meta.outputs.tag_name }}
          name: ${{ steps.release_meta.outputs.release_name }}
          target_commitish: ${{ github.sha }}
          make_latest: true
          generate_release_notes: true
          file_glob: true
          files: |
            apps/electron/out/make/**/*.dmg
            apps/electron/out/make/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-router-macos-x64
          path: |
            apps/electron/out/make/**/*.dmg
            apps/electron/out/make/**/*.zip
          if-no-files-found: error
