name: Build macOS x64

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  build-macos-x64:
    runs-on: macos-13
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Electron app (macOS x64)
        run: pnpm --filter @mcp_router/electron run make:x64

      - name: Upload macOS x64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-router-macos-x64
          path: |
            apps/electron/out/make/**/*.dmg
            apps/electron/out/make/**/*.zip
          if-no-files-found: error
